### ISSUE TITLE
Bug in random number generation

### ISSUE THREAD

**Issue by rfourquet** [JuliaMath/DoubleFloats.jl#10]
In the current implementation of `rand` for `DoubleFloat`, there is a hidden bug, happening when the generated `UInt64` is close to `typemax(UInt64)`. E.g., reproducing the implementation, with `T == Float64`:
```julia
u  = rand(rng, UInt64)
f  = Float64(u)
uf = UInt64(f)
ur = (uf > u ? uf - u : u - uf)
rf = Float64(ur)
v = DoubleFloat(T(5.421010862427522e-20 * f), T(5.421010862427522e-20 * rf))
```
There are two errors:
1. the last line should be `DoubleFloat{T}(...)`, because the constructor without specified type parameter doesn't normalize the two values. For example, taking `u == typemax(UInt)`, `v` will have both fields equal to `1.0`.
2. even after fixing this, we still have `v == 2.0` (still for `u == typemax(UInt)`), which is wrong given that `rand` should produce a number in `[0, 1)`

**Comment by JeffreySarnoff** [comment]
OK -- let's get better.  (a) do not be captive to present source code [it has distinct influences that may not cooperate in the best case scenario] (b) provide constructor with any actionable non-standard case that may arise (c) use an external metrical scale to ensure T(hi::T | lo::T)  === hi

**Comment by JeffreySarnoff** [comment]
reworked
