### ISSUE TITLE
`norm(v, Inf)` fails when `v` is empty

### ISSUE THREAD

**Issue by mtanneau** [JuliaMath/DoubleFloats.jl#105]
Calling `norm(v, Inf)` internally results in a error when `v` is empty.
```julia
using DoubleFloats
using LinearAlgebra

u = ones(Double64, 0)

norm(u, Inf)
```
results in the following error:
```
ERROR: ArgumentError: reducing over an empty collection is not allowed
Stacktrace:
 [1] _empty_reduce_error() at ./reduce.jl:212
 [2] reduce_empty(::Function, ::Type) at ./reduce.jl:222
 [3] mapreduce_empty(::typeof(identity), ::Function, ::Type) at ./reduce.jl:247
 [4] _mapreduce(::typeof(identity), ::typeof(max), ::IndexLinear, ::Array{Double64,1}) at ./reduce.jl:301
 [5] _mapreduce_dim at ./reducedim.jl:312 [inlined]
 [6] #mapreduce#584 at ./reducedim.jl:307 [inlined]
 [7] mapreduce at ./reducedim.jl:307 [inlined]
 [8] _maximum at ./reducedim.jl:657 [inlined]
 [9] _maximum at ./reducedim.jl:656 [inlined]
 [10] #maximum#591 at ./reducedim.jl:652 [inlined]
 [11] maximum at ./reducedim.jl:652 [inlined]
 [12] norm(::Array{Double64,1}, ::Float64) at /home/mtanneau/.julia/packages/DoubleFloats/N3du0/src/math/linearalgebra/support.jl:13
 [13] top-level scope at REPL[5]:1
```
The error comes the internal call to `maximum`/`minimum` over an empty array here
https://github.com/JuliaMath/DoubleFloats.jl/blob/ee0632f966afc21968b89e8b0319b7eb895ccca7/src/math/linearalgebra/support.jl#L13
and here
https://github.com/JuliaMath/DoubleFloats.jl/blob/ee0632f966afc21968b89e8b0319b7eb895ccca7/src/math/linearalgebra/support.jl#L25

This also causes `normalize(v, Inf)` to error, since it computes `norm(v, Inf)` internally.

Possible fix: first check if array is empty, and return 0 if it is. Happy to PR if it is satisfactory.

**Comment by JeffreySarnoff** [comment]
This is the default behavior for Julia:
```
julia> using LinearAlgebra

julia> norm([])
ERROR: MethodError: no method matching zero(::Type{Any})
Closest candidates are:
  zero(::Type{Union{Missing, T}}) where T at missing.jl:105
  zero(::Type{Missing}) at missing.jl:103
  zero(::Type{LibGit2.GitHash}) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\LibGit2\src\oid.jl:220
  ...
Stacktrace:
 [1] zero(::Type{Any}) at .\missing.jl:105
 [2] norm(::Array{Any,1}, ::Int64) at D:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.4\LinearAlgebra\src\generic.jl:605 (repeats 2 times)
 [3] top-level scope at REPL[2]:1
```

**Comment by JeffreySarnoff** [comment]
You are welcome to convince me that the norm of [] is zero.

**Comment by mtanneau** [comment]
> This is the default behavior for Julia

I beg to differ.

Your example fails because the eltype of `[]` is `Any`, which causes `zero(eltype([])` to fail [here](https://github.com/JuliaLang/julia/blob/8256be444d4420b485893993cd3f391be397ad1b/stdlib/LinearAlgebra/src/generic.jl#L605). But typed vectors of length `0` work fine
```julia
julia> using LinearAlgebra
julia> norm(Float64[])
0.0
julia> norm(Float64[], Inf)
0.0
julia> norm(Int[], Inf)
0.0
julia> norm(BigFloat[])
0.0
```
exactly because this check is performed at the first line of the function:
```julia
isempty(itr) && return float(norm(zero(eltype(itr))))
```

> You are welcome to convince me that the norm of [] is zero.

The p-norm of a `n`-dimensional vector is defined as
```math
|x|_p = (|x_1|^p + |x_2|^p +... + |x_n|^p)^(1/p)
```
When `n` is zero, the inner sum is empty, thus it is equal to zero, and therefore `|x|_p = 0`. for all `p`.
Taking the limit when `p -> ∞` yields `|x|_∞ = 0`.

If you don't like the limit, you can use the fact that, in a finite-dimensional space, [all norms are equivalent](https://math.mit.edu/~stevenj/18.335/norm-equivalence.pdf), thus if `x` has norm zero form some norm `|.|_a`, then its norm is zero for any norm `|.|_b`.

**Comment by JeffreySarnoff** [comment]
ok -- give me a PR

**Comment by JeffreySarnoff** [comment]
well it is not that conversions are missing .. it seems to be in the implementation of isapprox for Double64s .. working on it.
```
julia> x = Double64(3.00000000001)
julia> isapprox(x, 3.0)
true

julia> isapprox(x, Double64(3))
false
```
