### ISSUE TITLE
Are you forgot about round after each operation?

### ISSUE THREAD

**Issue by munrocket** [JuliaMath/DoubleFloats.jl#11]
Look at this article please, he use round function after each iteration.
https://www.codeproject.com/Articles/884606/The-double-double-type

**Comment by JeffreySarnoff** [comment]
"No. I have not forgotten how to implement the algorithms that I have selected."

It is good to be thorough, particularly when developing floating point types that work at precisions in excess of the machine's own microprocessor delivered capabilities. I am glad you decided to ask.  

I am familiar with the software library you reference. It is a cleaner refactoring of an older doubledouble package. You saw something like this:

the webpage's sketch of how the operation is coded
```
function Fast2Sum(a, b)
    s  = RN( a + b )
    t1 = RN( s - a )
     t  = RN( b - t1 )
     return(s, t)
end
```
And, reasonably, read the lines patterned `result = RN(a op b)` as
 "temp = a op b; result = RoundNearest(temp)"  or as
"temp = RoundNearest(a op b); return temp"

It may be of interest for you to know that when the intial doubledouble C library was written, that code actually did introduce an extra pair of calls to reset and restore the internal state of Intel's floating point processor control unit.. In that code there was additional rounding happening everywhere   because the authors found it necessary to avoid any possibility an external task might have alered that state for its own purposes while the floating point work still was occuring..

Let's look at the actual code for that addition operation from the author you reference.
(from the file `inline.h`)
```
/* Computes fl(a+b) and err(a+b).  Assumes |a| >= |b|. */
inline double quick_two_sum( double a, double b, double& err )
{
    double s = a + b;
    err = QD_ISFINITE( s ) ? b - (s - a) : 0.0;
    return s;
}
to see what is happening more easily, I will remove the check ISFINITE here
/* Computes fl(a+b) and err(a+b).  Assumes |a| >= |b|. */
inline double quick_two_sum( double a, double b, double& err )
{
    double s = a + b;
    err = b - (s - a)
    return s;
}

Note that the actual source code is not written like this
/* Computes fl(a+b) and err(a+b).  Assumes |a| >= |b|. */
inline double quick_two_sum( double a, double b, double& err )
{  // the "RN(_)s" below do not occur in the source code 
    double s = RN(a + b);
    err = RN(b - (s - a));
    return s;
}

What you took to be an insertion of a rounding step at each arithmetic operation `RN` actually conveys "the rounding that occurs automatically and within the excecution of this arithnmetic operation is one where the result is computed with RoundNearest semantics."  It is not adding a step.  It is asserting that microprocessor is a state which, when providing an arithmetic operation, preserves this intent.

"RN( a + b )" means  within the context where RoundNearest occurs, do this: a + b 

again, thank you for the question -- others may come across this as you have

**Comment by munrocket** [comment]
Thank you for detailed and quick answer! I am recently wrote my mandelbrot set realization and finded that arbitrary precision alorithm is slow. Now I started to think about porting your library in javascript.

**Comment by munrocket** [comment]
Also I think this algorithm useful in WebGL shader language GLSL.

**Comment by munrocket** [comment]
Hello, I maked same library in js and all is perfect except one glitch that i found.
Sometimes double-double addition and subtraction not additive inversed.

Example:
julia> log2 = Double64(0.6931471805599453, 2.3190468138462996e-17)
julia> pi = Double64(3.141592653589793, 1.2246467991473532e-16)
julia> x = log2 - ((log2 + pi) - pi) 
julia> showtyped(parse(Double64, stringtyped(x)))
Double64(-1.1102230246251565e-16, -4.959269606797132e-33)
Can you please check this result?

And also Double64(0.3, 0)-Double64(0.1, 0) ?
For me it's Double64(0.19999999999999998, 0).

**Comment by JeffreySarnoff** [comment]
```
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.1.0-DEV.125 (2018-08-26)
 _/ |\__'_|_|_|\__'_|  |  Commit a2a1506* (1 day old master)
|__/                   |

julia> using DoubleFloats
[ Info: Recompiling stale cache file /home/jas/.julia/compiled/v1.1/DoubleFloats/KzTCm.ji for DoubleFloats [497a8b3b-efae-58df-a0af-a86822472b78]

julia> log2 = Double64(0.6931471805599453, 2.3190468138462996e-17)
6.9314718055994530941723212145817600e-01

julia> pi = Double64(3.141592653589793, 1.2246467991473532e-16)
3.1415926535897932384626433832795058

julia> x = log2 - ((log2 + pi) - pi)
-3.079999999999999999999999999999999e-33

julia> showtyped(parse(Double64, stringtyped(x)))
Double64(-3.0814879110195774e-33, 0.0)
julia> 

julia> Double64(0.3)-Double64(0.1)
1.9999999999999998334665463062265188e-01

julia> Double64(3)/10-Double64(1)/10
2.0000000000000000000000000000000092e-01
```

Double64(0.3) == Double64(Float64(0.3)) != Double64(3)/10

Double64(0.3, 0) is not legal -- though I will change that
```
julia> Double64(0.3, 0.0)
2.9999999999999998889776975374843460e-01

julia> Double64(3)/10
3.0000000000000000000000000000000061e-01
```

let me know if something above is unclear

**Comment by JeffreySarnoff** [comment]
do `pkg> up` and note, I am developing DoubleFloats for Julia v1 (not earlier versions)

**Comment by munrocket** [comment]
Thanks. I guess (0.3, 0) is not normalized. For example Double(0.3, 1e-25)-Double(0.1, 1e-25) works with double precision.

**Comment by JeffreySarnoff** [comment]
right -- those are different numbers.  Double(0.3,0.0) is highpart = 0.3, lowpart = 0.0

**Comment by munrocket** [comment]
We have some rounoff error in DWTimesFP and DWDivFP
```
julia> pi = Double64(MathConstants.pi)
3.1415926535897932384626433832795058

julia> pi - pi * 0.1 * 10
-1.7439342490043156352e-16

julia> pi - pi / 0.1 / 10
1.7439342490043158200999999999999999e-16

julia> d64"123" - d64"123" * 0.1 * 10
-6.827871601444712723609999999999999e-15
```
I guess same issue in QD library from C++ because it the same algorithm.

**Comment by JeffreySarnoff** [comment]
Thank you for noticing.  Its a promotion glitch, not an algorithmic one:
```julia
julia> d64"123" - d64"123" * 0.1 * 10
-6.827871601444712723609999999999999e-15

julia> d64"123" - d64"123" * d64"0.1" * d64"10"
0.0
```

**Comment by munrocket** [comment]
Why do you think that this is not an algorithmic problem with DWTimesFP/DWDivFP since we claim that calculated with double-double precision? Also can you share your favorite book about floating point expansion? I can't find strict proof of double-double * double algorithm. I noticed that you have some references in code.

**Comment by JeffreySarnoff** [comment]
If it were an algorithmic problem then doing the computation with each number explicitly (and individually) introduced as a Double64 value should encounter that `algorithmic problem`, but it does not:

```
julia> d64"123" - d64"123" * d64"0.1" * d64"10"
0.0
```

**Comment by JeffreySarnoff** [comment]
My most reliable source code that does arithmetic with 2, 3 or 4 floating point values and returns two or more floating point values of decreasing significance is gathered (here)[https://github.com/JeffreySarnoff/ErrorfreeArithmetic.jl.  While I do not assert the correctness of the contents, it is code that I have refined.

If you really want to do so, suggest some deep testing to verify the likelihood that they work as expected.
You could post it here and I will go through that with you.

**Comment by JeffreySarnoff** [comment]
There are times, particularly with parsing, that I use BigFloat as an intermediate format.  I do this because (a) very little computational time is expected to be in parsing (parse infile once, store the result, use the result) and (b) I have little personal interest in parsing of that nature.

**Comment by JeffreySarnoff** [comment]
This is how its done (Fortran -- readable and highly informative)
[DQFUN by David Bailey](http://www.davidhbailey.com/dhbsoftware/dqfun-v01.tar.gz)

**Comment by munrocket** [comment]
Thanks, I will check it definitely.

**Comment by JeffreySarnoff** [comment]
Start a notebook.

**Comment by JeffreySarnoff** [comment]
Please let me know of any occasion where you find some incongruity with program source text I wrote.

**Comment by munrocket** [comment]
Yes, sure. I plan to release the minimal version first with basic operation and covertion.

**Comment by munrocket** [comment]
Simple question. In mul313 variable q1 jumped out from nowhere?

**Comment by JeffreySarnoff** [comment]
hehehe -- good catch, There are a few other anomalies I found last night.  I had not noticed this one.

**Comment by munrocket** [comment]
I am waiting for fix :) It's basic block for triple-word float.

**Comment by JeffreySarnoff** [comment]
... This weekend ..

**Comment by JeffreySarnoff** [comment]
fixed in version 0.1.11 (tagged latest master, pending merge)

**Comment by munrocket** [comment]
Thanks!

**Comment by JeffreySarnoff** [comment]
sure -- use latest master v0.2.0 (not yet merged) for correct Project.toml and REQUIRE [the rest is the same as v0.1.11]

**Comment by munrocket** [comment]
Thank you for your patience, Jeffrey, my [library](https://github.com/munrocket/double.js) works perfectly in my [project](https://munrocket.github.io/deep-fractal/) and now I thinking about arbitrary precision like in MPFR or ArbFloat.jl in CPU or even GPU.

What do you think, is *Adaptive precision floating-point arithmetic and fast robust geometric predicates* algorithm by R. J. Shewchuk is siutable for GPU calculations? Can it be parallelized? I think it will be a great optimization for calculation some heavy equation with 2^8 accurate digit in cycle with one draw call.

**Comment by JeffreySarnoff** [comment]
Shewchuck's work seems less suitable for the GPU.  There is more modern work along the same lines, work that draws heavily from his and injects some current technology.  Search "floating-point expansions".

**Comment by munrocket** [comment]
https://hal.archives-ouvertes.fr/hal-01298206v2/document

**Comment by JeffreySarnoff** [comment]
yup and they developed the work in CAMPARY 
some slides: http://homepages.laas.fr/mmjoldes/Exposes/exposeICMS.pdf
the source code: http://homepages.laas.fr/mmjoldes/campary/campary_01.06.17.tar.gz

**Comment by munrocket** [comment]
Finally fixed a problem with parsing in Double.js, thank for your help.

**Comment by JeffreySarnoff** [comment]
😃
