### ISSUE TITLE
Tests failed on nightly due to Grisu being removed from Julia

### ISSUE THREAD

**Issue by KristofferC** [JuliaMath/DoubleFloats.jl#112]
https://github.com/JuliaMath/DoubleFloats.jl/blob/bc488df654abc4120806fed21ba0e78e6717134c/test/legacy.jl

doesn't work anymore.

**Comment by JeffreySarnoff** [comment]
Thank you. I am (trying to) register the fix.

**Comment by JeffreySarnoff** [comment]
automerge pending
