### ISSUE TITLE
triple code status ? 

### ISSUE THREAD

**Issue by lrnv** [JuliaMath/DoubleFloats.jl#114]
Hey, 

Reading the documentation, i saw in the reference some things about triples. Looking at the code, there is indeed code for Triple64. What is the current state of this implementation ? Since it is not documented, i was wandering if it was still a WIP or if Triple64 was already usable as a drop-in replacement for Double64.

**Comment by JeffreySarnoff** [comment]
It was coded to provide extra precision in Double64 elementary functions, if needed.  The type does not provide a generally useable implmentation.  Long story short, it never was to be an exported type and is no longer WIP.  If you need greater precision than Double64 with better performance than BigFloat. I recommend getting into ArbNumerics.jl
