### ISSUE TITLE
Double128 using Quadmath's Float128

### ISSUE THREAD

**Issue by lrnv** [JuliaMath/DoubleFloats.jl#115]
Hey, 

I am trying to implement some equivalent of Double64, but based on Float128 from Quadmath.jl. 

After a discourse talk [there](https://discourse.julialang.org/t/doublefloats-jl-double128-quad64/51049/6), I come to you for guidance. 

After some more reading of your code, it seems like copying the Double64 methods and constructors to match the same construct but on Float128 instead of Float64 should be enough. Am i missing something ? 

Since you already depend on Quadmath, there is no need for additional dependency.

Looking forward to read your oppinon about this.

Edit: While browsing your code, i do add questions / notes here

- It seems that `Float128 <: Base.IEEEFloat` is false. Will that be a big issue ? 
- But `Float128 <: AbstractFloat` is true.
- What are the conditions that Float128 need to meet to be a `FloatWithFMA` ?
- The constants in src/doubletriple/double_consts.jl and src/doubletriple/triple_consts.jl should not be a problem.
- src/doubletriple/triple_pi.jl seems more problematic to port.
- All the scr/type folder seems quite easy to port, since behaviors are quite general, assuming that we can make `Float 128 <: IEEEFloat`
- All the src/math/prearith folder seems given, again if `Float 128 <: IEEEFloat`
- I'll stop my reading htere for today. 

All over, it seems like, as the quadmath.jl readme says, "[Quadmath.jl] is a Julia interface to libquadmath, providing a Float128 type corresponding to the IEEE754 binary128 floating point format.". Hence adding it to the IEEEFloat Union, or some other union that we create to not interfere with base, should work.

**Comment by JeffreySarnoff** [comment]
While getting simple arithmetic to work with doubled Float128s is not difficult given available code, supporting elementary functions (exp, log, sin, atan, cosh, atanh ...) is an entirely different matter.  The elementary functions are carefully coded for Double64s and that code is not going to do anything for doubled Float128s.  There are implementations of "quad-doubles" that do this (not in Julia) and a quick look shows there is much more code involved .. so it runs much slower.  If you want that sort of precision, I would suggest ArbNumerics.jl.

**Comment by JeffreySarnoff** [comment]
Closing .. nothing to do that fits the design
