### ISSUE TITLE
Dependencies overwriting methods

### ISSUE THREAD

**Issue by pearlzli** [JuliaMath/DoubleFloats.jl#116]
When I load DoubleFloats, I get some very long warnings about GenericLinearAlgebra (v0.2.4) overwriting GenericSVD (v0.3.0) and GenericSchur (v0.4.0) methods, similar to those on [this Discourse post](https://discourse.julialang.org/t/genericlinearalgebra-overwrites-methods-from-genericschur-and-genericsvd/35056) (also me, from a while ago), [this GLA issue](https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/issues/60), and [this GSVD issue](https://github.com/JuliaLinearAlgebra/GenericSVD.jl/issues/2). DoubleFloats depends on all three:

DoubleFloats -> {GenericSVD, GenericSchur, Polynomials -> GenericLinearAlgebra}

The GLA issue linked above recommends not using both GLA and GSVD at the same time, since GLA already implements a generic SVD. Would it be possible to have DoubleFloats use only GLA?

**Comment by GregPlowman** [comment]
`Polynomials v1.1.13` (released 4 days ago) introduced dependency on `GenericLinearAlgebra` 
https://github.com/JuliaMath/Polynomials.jl/pull/297

Pinning `Polynomials v1.1.12` might be a temp workaround.

**Comment by JeffreySarnoff** [comment]
Thank you for the insight.  Considering possibilities ...

**Comment by davidanthoff** [comment]
I started an attempt to fix this at https://github.com/JuliaLinearAlgebra/GenericLinearAlgebra.jl/pull/71.

**Comment by JeffreySarnoff** [comment]
super!

**Comment by JeffBezanson** [comment]
Why does this package depend on GenericSVD? Does that mean GenericSVD is just not generic enough?

**Comment by JeffreySarnoff** [comment]
At the time, LinearAlgebra was not generic enough and GenericSVD did provide `svd` and friends that worked with DoubleFloats.  So it depends on GenericSVD to provide `svd`.  I know there have been changes in LinearAlgebra .. I will check if that now works generically enough to cover DoubleFloats.

**Comment by JeffreySarnoff** [comment]
@JeffBezanson GenericSVD is necessary to provide `svd`, `svdvals` etc.
LinearAlgebra, if it provides generic versions, does not provide generic versions that are generic enough.

**Comment by JeffreySarnoff** [comment]
maybe all is alright now -- reopen otherwise
