### ISSUE TITLE
Inf norm of a Complex{Double64}

### ISSUE THREAD

**Issue by pnavaro** [JuliaMath/DoubleFloats.jl#120]
Hi,
I have an issue here 

```julia
julia> using DoubleFloats
[ Info: Precompiling DoubleFloats [497a8b3b-efae-58df-a0af-a86822472b78]

julia> v = Complex{Double64}[1im]
1-element Array{Complex{Double64},1}:
 0.0 + 1.0im

julia> using LinearAlgebra

julia> norm(v, Inf)
0.0

```

**Comment by JeffreySarnoff** [comment]
I'll take a look .. the bug is not immediately obvious.
Meanwhile, substituting `typemax(Int)` for `Inf` in `norm(v, Inf)` may work.

**Comment by fgerick** [comment]
I was going to open another issue, but I assume it's related: 

`normalize!([0,0,1.1]) # => [0.0,0.0,1.0]`, but `normalize!([0,0,df64"1.1"]) # => [NaN,NaN,NaN]`

**Comment by fgerick** [comment]
I narrowed it down to:

```julia
julia> inv(prevfloat(typemax(Double64)))
NaN

julia> @which inv(prevfloat(typemax(Double64)))
inv(x::DoubleFloat{T}) where T<:Union{Float16, Float32, Float64} in DoubleFloats at /Users/felixger/.julia/packages/DoubleFloats/lKM0D/src/math/ops/arith.jl:6
```

**Comment by JeffreySarnoff** [comment]
This needs to be fixed.
```
julia> typemax(Float64), prevfloat(typemax(Float64))
(Inf, 1.7976931348623157e308)

julia> typemax(Double64), prevfloat(typemax(Double64))
(Inf, Inf)
``` 
`prevfloat(typemax(T))` should be `floatmax(T)` for `T<:AbstractFloat`
`nextfloat(typemin(T))` should be `floatmin(T)` for `T<:AbstractFloat`

**Comment by JeffreySarnoff** [comment]
moved up my todo list :)

**Comment by JeffreySarnoff** [comment]
In the branch #infnorm, I have fixed the prevfloat/nextfloat problem, and that fixed the normalize! issue.  The issue with norm remains, looking into that.

**Comment by JeffreySarnoff** [comment]
The fix has been merged locally. The new version is pending Julia's pkg update.

**Comment by pnavaro** [comment]
Thank you

**Comment by pnavaro** [comment]
Dear @JeffreySarnoff , in  v1.1.18 the bug is still there.

**Comment by pnavaro** [comment]
Ok it works, sorry for the noise, thanks again

```julia
julia> using DoubleFloats
[ Info: Precompiling DoubleFloats [497a8b3b-efae-58df-a0af-a86822472b78]

julia> v = Complex{DoubleFloat}[1im]
1-element Array{Complex{DoubleFloat},1}:
 0.0 + 1.0im

julia> using LinearAlgebra

julia> norm(v, Inf)
1.0
```

**Comment by JeffreySarnoff** [comment]
no problem
