### ISSUE TITLE
Bump Polynomials?

### ISSUE THREAD

**Issue by GregPlowman** [JuliaMath/DoubleFloats.jl#123]
Can `DoubleFloats` upgrade `Polynomials` dependency to latest version (`v2.0`)?
I don't think the latest version of `Polynomials` depends on `GenericLinearAlgebra`, so this shouldn't reintroduce issue #116?

**Comment by JeffreySarnoff** [comment]
sure .. thanks

**Comment by JeffreySarnoff** [comment]
should be happening

**Comment by GregPlowman** [comment]
Thanks!

**Comment by JeffreySarnoff** [comment]
Any time, I would prefer if this activity just happened whenever a maintained pkg's dependency upversions -- and there is no need for me to watch that happen.  If a dependency upversions and contains a change that causes the pkg to get something wrong that had be handled right .. that fact will come to my attention quickly.

**Comment by GregPlowman** [comment]
CompatHelper might get you half way there:

https://github.com/JuliaRegistries/CompatHelper.jl
