### ISSUE TITLE
eigvals and eigvecs no longer work with Double64

### ISSUE THREAD

**Issue by Dedavond** [JuliaMath/DoubleFloats.jl#126]
Example:
```Julia
using LinearAlgebra 
using GenericLinearAlgebra # v0.2.5
using DoubleFloats # v1.1.21

M = convert.(Double64, [1 2 3; 4 1 6; 7 8 1])
eigvals(M) #Gives Error
eigvecs(M) #Gives Error

S  = convert.(Double64, [1 2 0; 2 1 3; 0 3 1]) #Symmetric Matrix
eigvals(S) #Works
eigvecs(S) #Gives Error
```
Julia Version 1.5.2

**Comment by JeffreySarnoff** [comment]
hmmm

**Comment by JeffreySarnoff** [comment]
if you add `using GenericSchur` it will work --
I am going to update master accordingly
Thank you

**Comment by JeffreySarnoff** [comment]
Should be fixed -- just merged. Let me know if there are any more issues.

**Comment by Dedavond** [comment]
Thanks! That fixed it for me.
I have also been having an issue with using Symmetric with an array of Double64 datatype in the eigvals (and eigvecs) functions, that is:
```Julia
using LinearAlgebra 
using GenericLinearAlgebra
using GenericSchur
using DoubleFloats

S  = convert.(Double64, [1 2 0; 2 1 3; 0 3 1]) #Symmetric Matrix
eigvals(S) #Works
eigvecs(S) #Now works
eigvals(Symmetric(S)) # Error
eigvecs(Symmetric(S)) # Error
```
where eigvals should use an optimised method for Symmetric (https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#Matrix-factorizations) whereas now the eigvals (eigvecs) when using Double64 return complex results (with 0 complex component) even for symmetric matrices.

**Comment by JeffreySarnoff** [comment]
Does it return the correct numbers with a 0 imaginary part, or does it error when trying, or does it return incorrect numbers?

**Comment by Dedavond** [comment]
eigvals(S) returns correct numbers with 0 imaginary part, eigvals(Symmetric(S)) gives an error when trying. Similar behaviour for eigvecs.

**Comment by JeffreySarnoff** [comment]
DoubleFloats no longer `using GenericSchur` (it broke more than it fixed) so you need to do that for yourself
