### ISSUE TITLE
plane rotations or givens rotations are slow for Double64 due to Int64 conversion using BigFloats

### ISSUE THREAD

**Issue by dgleich** [JuliaMath/DoubleFloats.jl#128]
The crux of the issue: the `floatmin2` function used in computing plane rotations or givens rotations by the LinearAlgebra base library `givens` function falls into the Int64(Double64...) conversion, which then allocates BigInt/BigFloat calls and can be made much faster in a few different ways

Here's the code:

    floatmin2(::Type{T}) where {T} = (twopar = 2one(T); twopar^trunc(Integer,log(floatmin(T)/eps(T))/log(twopar)/twopar))

- I don't know why the Julia compiler can't realize that this is a constant expression for a type, but ... alas

Benchmarking code...

```
using DoubleFloats, LinearAlgebra
function plane_rotation(f::T, g::T) where T
  g, r = givens(f, g, 1, 2)
  return g.c, g.s, r
end

function myfunc(x, y, z)
  for i=1:length(x)-1
    c,s,r = plane_rotation(x[i],x[i+1])
    y[i] = c
    z[i] = s
  end
end

using BenchmarkTools
println("Float64")
@btime myfunc(x,y,z) setup=begin
  x = ones(50)
  y = similar(x)
  z = similar(x)
end

println("Double64")
@btime myfunc(x,y,z) setup=begin
  x = Double64.(ones(50))
  y = similar(x)
  z = similar(x)
end
```

```
  274.894 ns (0 allocations: 0 bytes)
Double64
  184.260 μs (1078 allocations: 38.28 KiB)
```

Adding the explicit specialization

```
# specialize for Double64
#floatmin2(::Type{T}) where {T} = (twopar = 2one(T); twopar^trunc(Integer,log(floatmin(T)/eps(T))/log(twopar)/twopar))
import LinearAlgebra.floatmin2
LinearAlgebra.floatmin2(::Type{Double64}) = Double64(reinterpret(Float64, 0x2350000000000000), 0.0)
```

Gives

```
Double64
  7.636 μs (0 allocations: 0 bytes)
```

Possible fixes... (I'm using Double64 just as the stand-in double float type...) 

- Don't fix, just let users (like me) discover this when Double64 code and then figure out the patch above ... total time for me was about 60-90 mins.
- Explicitly overload floatmin2 as above in the Double64 with precomputed values (note, this is what Base uses for float64)
- Avoid BigInt/BigFloat in the integer conversions -- the specific line that does all the allocation in the above example is : `Base.Int64(x::DoubleFloat{T}) where {T<:IEEEFloat} = Int64(round(BigInt, BigFloat(HI(x)) + BigFloat(LO(x))))`; see below...
- Specialize givensAlgorithm in Base for Double64
- [Alt...] Maybe improve floatmin2 in base to enable it to realize these are constants... seems hard.

Trying to avoid BigInt/BigFloat in the integer conversions gives the initial crude approximation:

```
import Base.Int64
Base.Int64(x::DoubleFloat{Float64}) = Int64(HI(x)) + Int64(LO(x))
```

which gives the following performance

```
Double64
  143.258 μs (0 allocations: 0 bytes)
```

so it fixes allocations, but still recomputes floatmin2 each time. 

Since there are various other overloads for base functions and linear algebra, it seems like the simplest fix is just to add specializations for

floatmin2 to DoubleFloats

Would such a pull-request be useful?

**Comment by JeffreySarnoff** [comment]
I will be changing most uses of BigFloats to use Quadmath, for performance while keeping intermediate accuracy reliable (here, extended  ~16 bits)

**Comment by JeffreySarnoff** [comment]
Yes please do the PR
