### ISSUE TITLE
Sign error in `cispi`

### ISSUE THREAD

**Issue by eschnett** [JuliaMath/DoubleFloats.jl#139]
According to its definition, `cispi(x) = cospi(x) + im * sinpi)x)`. Internally it is likely to use `sincos` to speed up evaluation. For certain arguments the sign is wrong:

```Julia
julia> x = DoubleFloat(1.083533835485919)
1.083533835485919

julia> cispi(x)
0.9657626055706809 + 0.2594274266174056im

julia> cospi(x) + im * sinpi(x)
-0.9657626055706809 - 0.2594274266174056im
```

**Comment by JeffreySarnoff** [comment]
nice catch

**Comment by JeffreySarnoff** [comment]
fixed on master
I had not defined `cis` or `cispi` .. some fallback process was fooled.
I added those and added `sincos`, `sincospi` to support the calculaitons.
Right now, `cis` [`cispi`] does not use `sincos` [`sincospi`], and there
is no time savings. Before I merge this, there is that to revisit and
a few tests to add.

**Comment by JeffreySarnoff** [comment]
should work now -- with new version just merged.
Let me know if it is not ok.
