### ISSUE TITLE
Inf/a yields NaN

### ISSUE THREAD

**Issue by GVigne** [JuliaMath/DoubleFloats.jl#142]
Hi!
While trying to solve an issue in the DFTK package  (#https://github.com/JuliaMolSim/DFTK.jl/issues/428), I encountered a strange behaviour with Double64:
```julia
julia> Double64(Inf)/Double64(2.0)
Inf
julia> Float64(Inf)/Double64(2.0)
NaN
```
Is this a bug or is this the expected result? If so, why was this convention chosen?

**Comment by JeffreySarnoff** [comment]
It is a bug .. both should be `Inf` will fix quickly -- thank you

**Comment by JeffreySarnoff** [comment]
fixed in master -- merge pending
Thanks again -- good find.
