### ISSUE TITLE
Double64 seems have problem for the string function and less precision.

### ISSUE THREAD

**Issue by Yangkui1971** [JuliaMath/DoubleFloats.jl#144]
# Do test for DoubleFloat， In this case DoubleFloat precision is less than Float64
using DoubleFloats
a=Double64(111)
b=Double64(100000)
c=a/b
println("See  Double64  a/b:" * string(c))
c=c * c
c=c * c
c=c * c
println("See  Float64  converted:" * string(Float64(c))) # Why converting  to Float64 is correct, but it is wrong on showing on screen?
println("See Double64  to String:" * string(c)) # Mistakes for the string function
println("See Actual  Double64 :" * "2.3045377 " * string(c-Double64("2.3045377e-24"))) # Show more figures by substracting the front figures
# It tell that the Double64 "string" founction is not corrrect
# In comparison with Big Float
d=BigFloat(111)
e=BigFloat(100000)
f=d/e
f=f * f
f=f * f
f=f * f
println("See BigFloat  to String:" * string(f))

**Comment by Yangkui1971** [comment]
The print-out is :
See  Double64  a/b:0.0011100000000000000000000000000000
See  Float64  converted:2.3045377697175683e-24
See Double64  to String:2.3045377697175660503165553197250634e-24
See Actual  Double64 :2.3045377 6.9717570777071673153243990596594752e-32
See BigFloat  to String:2.304537769717568099999999999999999999999999999999999999999999999999999999999897e-24

The real answer is: 2.3045377697175681e-24,  Float64 precision is better.

**Comment by JeffreySarnoff** [comment]
fixed (merge pending). good that you found this and informed me.  thank you.

**Comment by JeffreySarnoff** [comment]
Merged. Please use `pkg> up` to get the current version

**Comment by JeffreySarnoff** [comment]
It has not yet merged -- restarting with unrelated adjustment

**Comment by JeffreySarnoff** [comment]
Now it has merged -- let me know if you find another issue.

**Comment by JeffreySarnoff** [comment]
Well, another user did -- now fixed in master, merge pending
