### ISSUE TITLE
Should `floatmax` be slightly larger?

### ISSUE THREAD

**Issue by haampie** [JuliaMath/DoubleFloats.jl#15]
Right now `floatmax` sets the `lo` bit to zero, but maybe it should be as large as possible. For example:

```julia
julia> Double16(6.55e4, 15)
6.5519e+04
julia> Double16(6.55e4, 15) > floatmax(Double16)
true
```

**Comment by JeffreySarnoff** [comment]
Good question, and one I have considered.  Doubled types allow the hi part to be much more significant than the lo part `Double64(1.0e200, 1.0e-200)`.  `floatmax` is used in some places by other packages (maybe GenericSVD or LinearAlgebra or Quaternions) as an algorithmic stopping point or algorithmic condition.  If we make `lo` non-zero, some other stuff in other packages chokes.  Eventually, this should get sorted out (on their end) when taking_numeric_apis_seriously is in vogue.

**Comment by JeffreySarnoff** [comment]
When the tests cover some external package interactions, it makes sense to try the change.  Otherwise we would likely mislead ourselves as to the suitability of the change in real use.

**Comment by JeffreySarnoff** [comment]
short form: If using the larger values had worked well when I defined them, I'd have used them.

**Comment by haampie** [comment]
Right. I'm asking because `maxintfloat(Double16) == 65519` in #16, and this value is larger than `floatmax(Double16)` at the moment. So then maybe `maxint(Double16)` should equal `maxfloat(Double16) == 65504` to be consistent.

**Comment by JeffreySarnoff** [comment]
oh -- yes I agree.  Doing that.

**Comment by JeffreySarnoff** [comment]
Use the version just merged, it has a few fixups and now supports div, rem, fld, cld, mod, divrem, fldmod also added d64"0.3" d32"1.7" as Double64(0.3) just converts the Float64(0.3) to a Double64.

**Comment by JeffreySarnoff** [comment]
fyi, maxintfloat and floatmax have been improved
