### ISSUE TITLE
How to cite/acknowledge your package in a publication?

### ISSUE THREAD

**Issue by nquesada** [JuliaMath/DoubleFloats.jl#153]
Hello everyone --- Your package has proven extremely useful to my students and myself; we would very much like to cite it, any preferences on how to do so? If you could provide a bibTeX entry would be super useful.

Once more, thanks for all the great work in here!

**Comment by JeffreySarnoff** [comment]
ok -- thank you

**Comment by JeffreySarnoff** [comment]
I added an CITATION.cff file.  This is the result from selecting "cite this file" on the right and choosing BibTeX.

@software{Sarnoff_DoubleFloats_2022,
author = {Sarnoff, Jeffrey and {JuliaMath}},
license = {MIT},
month = {6},
title = {{DoubleFloats}},
url = {https://github.com/JuliaMath/DoubleFloats.jl},
version = {1.2.2},
year = {2022}
}

**Comment by nquesada** [comment]
Thanks, just saw the button.
