### ISSUE TITLE
Compatability issue with Polynomials 4 

### ISSUE THREAD

**Issue by protogeezer** [JuliaMath/DoubleFloats.jl#173]
I tried (re)installing DoubleFloats and still got the squawk about requiring Polynomials 3...

**Comment by JeffreySarnoff** [comment]
I renamed master to main, if you have a local fork
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
see [new release](https://github.com/JuliaMath/DoubleFloats.jl/releases/tag/v1.2.5)
try `pkg> add DoubleFloats#main`

**Comment by protogeezer** [comment]
add DoubleFloats#main did the trick. Thanks.
