### ISSUE TITLE
Register latest version v1.2.5?

### ISSUE THREAD

**Issue by GregPlowman** [JuliaMath/DoubleFloats.jl#174]
I see the latest version updates the compat bound for `Polynomials`.
Is it possible to register this version (`v1.2.5`)?

**Comment by JeffreySarnoff** [comment]
I do not know why it did not autoregister.  I have asked for the merge on slack.

**Comment by JeffreySarnoff** [comment]
thanks for attention -- it should merge within the next 6 minutes

**Comment by JeffreySarnoff** [comment]
Merged!

**Comment by GregPlowman** [comment]
Thanks!
