### ISSUE TITLE
`x^n` allocates when `n` is an integer-float 

### ISSUE THREAD

**Issue by mjmcnelis** [JuliaMath/DoubleFloats.jl#182]
When I use the power operator `x^n`, it allocates when the exponent `n` is a `DoubleFloat` but takes on an integer value:
```julia
using DoubleFloats

@time Double64(5.0)^2             # 0.000002 seconds
@time Double64(5.0)^Double64(2.0) # 0.000015 seconds (11 allocations: 376 bytes)
@time 5^Double64(2.0)             # 0.000017 seconds (11 allocations: 376 bytes)
```
The second case applies to my situation where `x` and `n` are both the same type. The temp solution I'm working with right now overwrites two of the `^` methods defined in `src/math/elementary/explog.jl` as
```julia
using DoubleFloats: IEEEFloat

function Base.:(^)(r::DoubleFloat{T}, n::DoubleFloat{T}) where {T <: IEEEFloat}
    if isinteger(n)
        # return r^Int(n)        # original
        return r^Int(Float64(n)) # convert n to Float64 first
    else
       return exp(n * log(r))
    end
end

function Base.:(^)(r::Int, n::DoubleFloat{T}) where {T<:IEEEFloat}
    if isinteger(n)
        # return r^Int(n)        # original
        return r^Int(Float64(n)) # convert n to Float64 first
    else
        return exp(n * log(r))
    end
end
```
The original conversion of `n` from `DoubleFloat` to `Int` was allocating. If I look at `src/type/convert.jl` ln. 14
```julia
convert(::Type{I}, x::DoubleFloat{T}) where {T<:IEEEFloat, I<:Integer} = I(round(BigInt, BigFloat(HI(x))+ BigFloat(LO(x))))
```
it uses `BigFloat` and `BigInt`. I'm not sure why rounding is involved (e.g. `Int64(1.01)` doesn't round, it just throws an error), but it doesn't seem necessary when `isinteger(n) = true`. Instead, I make an intermediate conversion from `DoubleFloat` to `Float64` to fix the allocation issue:
```julia
@time Double64(5.0)^2             # 0.000001 seconds
@time Double64(5.0)^Double64(2.0) # 0.000002 seconds
@time 5^Double64(2.0)             # 0.000005 seconds
```

I'm using Julia 1.10.

**Comment by JeffreySarnoff** [comment]
thank you. merge pending.
