### ISSUE TITLE
bug in DWTimesDW2

### ISSUE THREAD

**Issue by nschaeff** [JuliaMath/DoubleFloats.jl#186]
[Line 172 of double.jl](https://github.com/JuliaMath/DoubleFloats.jl/blob/95cec825c40c90e6166162f306fdc03e945832a0/src/doubletriple/double.jl#L172) should be changed to 
`t0 = x_hi * y_lo`
instead of
`t0 = x_lo * y_lo`
otherwise the algorithm is NOT correct (you can check algorithm 11 in the reference paper).

**Comment by JeffreySarnoff** [comment]
Nice catch.  Fixed, Pkg merge pending.
