### ISSUE TITLE
use fma for a faster and more accurate sqrt

### ISSUE THREAD

**Issue by nschaeff** [JuliaMath/DoubleFloats.jl#187]
I suggest replacing the current implementation found here:
https://github.com/JuliaMath/DoubleFloats.jl/blob/c085185654507a6e73b6568a01a5c26fc47c0e0d/src/math/ops/op_dd_dd.jl#L59

with the following (pseudo-code), which is both much faster and a bit more accurate, thanks to fma:

```julia
function sqrt_dd_dd(x::Tuple{T,T}) where {T<:IEEEFloat}
    iszero(HI(x))) && return x
    signbit(HI(x)) && throw(DomainError("sqrt(x) expects x >= 0"))   # maybe we can remove this check? It will return nan anyway.

    ahi, alo = HILO(x)
    s = sqrt(ahi)
    d = fma(-s, s, ahi)    # ahi=s*s+d,  same order of magnitude than alo, so we can add alo safely below:
    d += alo               #  ahi+alo = s*s+d = s*s*(1+d/(s*s))   ==> sqrt(ahi+alo) = s*sqrt(1+d/s2) approx= s*(1+d/(2s2)) = s + d/(2*s)
    d = d/(s+s)
    return s,d
```

**Comment by JeffreySarnoff** [comment]
and the corresponding fix for cbrt?

**Comment by nschaeff** [comment]
For cbrt, you can't just use an fma to compute the error with respect to cbrt(hi), so it is a bit more involved.
But once we have the error, the correction is as straightforward.
I propose the following (quickly tested with python on 2 values). It assumes that cbrt gives an accurate result :

```julia
function cbrt_dd_dd(ahi, alo):
      c = cbrt(ahi)
      c2, c2l = two_prd(c,c)    # c*c
      c3, c3l = mul_ddfp_dd((c2,c2l), c)   # c*c*c this should be close to ahi and will allow us to compute the error
      d = ahi - c3    # this almost completely cancels out (except 1 or 2 bits), becoming on the same order of xl and alo
      d += (alo - c3l)    # we now have ahi+alo = c3 + d  ----> cbrt(ahi+alo) = c * cbrt(1+d/c3)  approx= c*(1+d/(3*c3)) = c + d/(3*c2)
      d = d/(3*c2)
      return c,d
```
It is OK with respect to accuracy, but I have no idea if it is better or worse than the current `cbrt_dd_dd` algo.

**Comment by nschaeff** [comment]
Breaking news: I just learned from one of the authors, that the algorithm I propose for sqrt has been published and analyzed by serious people. It is algorithm 8 from [Lefevre+ 2023](https://hal.science/hal-03482567/document), the relative error bound is 3.125 ulp.

**Comment by JeffreySarnoff** [comment]
nice -- will implement

**Comment by JeffreySarnoff** [comment]
merge pending
