### ISSUE TITLE
Some missing features 

### ISSUE THREAD

**Issue by saschatimme** [JuliaMath/DoubleFloats.jl#2]
First, good to see that this package takes form :) I just gave it a short spin and found a couple of things which are not working as intended.

There are a bunch of float specific functions not defined which cause different issues (e.g. you cannot take the square root of complex number at the moment). These include
- [ ] `realmin(::Type{Double{Float64,<:Emphasis})` and `realmax(:Type{Double{Float64,<:Emphasis})` 
- [ ] `typemin(:Type{Double{Float64,<:Emphasis})` and `typemax(:Type{Double{Float64,<:Emphasis})`
- [ ] `nextfloat(:: Double)`
- [ ] `eps(:Type{Double{Float64,<:Emphasis})`

Also it seems that `minmax` needs to be imported from Base
```julia
julia> abs(Double(rand())+2.0im)
ERROR: MethodError: no method matching minmax(::Double{Float64,Accuracy}, ::Double{Float64,Accuracy})
You may have intended to import Base.minmax
Closest candidates are:
  minmax(::T, ::T, ::T) where T at /Users/sascha/.julia/v0.7/DoubleFloats/src/support/maxmin.jl:71
  minmax(::T, ::T, ::T, ::T) where T at /Users/sascha/.julia/v0.7/DoubleFloats/src/support/maxmin.jl:91
Stacktrace:
 [1] hypot(::Double{Float64,Accuracy}, ::Double{Float64,Accuracy}) at /Users/sascha/.julia/v0.7/DoubleFloats/src/math/moremath.jl:4
 [2] abs(::Complex{Double{Float64,Accuracy}}) at ./complex.jl:259
 [3] top-level scope
```

Also the behaviour for `NaN` and `Inf` seems to be different than for `Float64`
```julia
julia> T = Double{Float64,Performance}
julia> T(NaN)
FastDouble(NaN, NaN)
julia> T(Inf) - 1
FastDouble(NaN, NaN)
julia> Inf - 1
Inf
```

**Comment by JeffreySarnoff** [comment]
Thanks -- (also play with the stuff that appears to be working pls)

**Comment by JeffreySarnoff** [comment]
oh -- there is no support for Complex as yet

**Comment by saschatimme** [comment]
Sure? Simple complex operations work for more.

I have another thing, which is more like a wish. I currently use excessively `muladd)` to speed up calculcations. Currently `Double` just uses the fallback `muladd(a, b, c) = a * b + c`. Do you know whether somebody considered this special case so far?

**Comment by JeffreySarnoff** [comment]
I do not understand your question about muladd.

**Comment by saschatimme** [comment]
I thought whether there exists a special method for operations of the form `a * b + c`, similar to that we have `square` for `a * a`. But this is probably way too fancy...

**Comment by JeffreySarnoff** [comment]
because `*` and `+` are error-free, there is usually a good outcome,
probably the way to do that would be to do `Double( (a * b) + triple(c) )`

**Comment by JeffreySarnoff** [comment]
or do you want exported that and call it fma?

**Comment by saschatimme** [comment]
Cool! I think to overload `Base.muladd` is the best. One application of this is Horner's method to evaluate polynomials which basically boils down to nested `muladd`s
```julia
julia> @macroexpand Base.Math.@horner a c1 c2 c3 c4 c5
quote
    #16031#t = a
    (Base.Math.muladd)(#16031#t, (Base.Math.muladd)(#16031#t, (Base.Math.muladd)(#16031#t, (Base.Math.muladd)(#16031#t, c5, c4), c3), c2), c1)
end
```

**Comment by JeffreySarnoff** [comment]
do that for Double and FastDouble?

**Comment by JeffreySarnoff** [comment]
```julia
julia> thi = Float64(tbig);tlo=Float64(tbig-thi);Double(thi,tlo)
Double(1.8674849396984466e14, 0.003872194160694882)

julia> muladd(d4,d2,d3)
Double(1.8674849396984466e14, 0.003872194160694882)

julia> d4*d2+d3
Double(1.8674849396984466e14, 0.0038721941606948826)
```

**Comment by JeffreySarnoff** [comment]
done ...

**Comment by JeffreySarnoff** [comment]
now to look at your early notes

**Comment by JeffreySarnoff** [comment]
(I am on this today -- its the best time to question and ask)

**Comment by JeffreySarnoff** [comment]
If you can massage this, I will include the result:
```julia

import Random: rand
using Random

function Random.rand(rng::AbstractRNG, S::Type{Double{T,E}}) where {T<:AbstractFloat, E<:Emphasis}
    u = Random.rand(rng, UInt64)
    f = Float64(u)
    uf = UInt64(f)
    ur = uf > u ? uf - u : u - uf

    Double(E, T(5.421010862427522e-20 * f), T(5.421010862427522e-20 * Float64(ur)))
end


Random.rand(::Type{Double{T,E}}) where {T<:AbstractFloat, E<:Emphasis} = Random.rand(Base.Random.GLOBAL_RNG, Double{T,E})
```

**Comment by JeffreySarnoff** [comment]
also, when you want the result of an external package's function to return FastDouble, it is a Good idea to call the func (e.g. rand) and then FastDouble(result) or (maybe check the result type `eltype`) and 
map(FastDouble, resultvec)

**Comment by JeffreySarnoff** [comment]
current master is the `pre-release`

**Comment by JeffreySarnoff** [comment]
v002 fixes some overlooked bugs and makes rand(Double, n) work better.
I need the FastDoubles to stay fast, as the Doubles now stay accurate.
