### ISSUE TITLE
sqrt(NaN)

### ISSUE THREAD

**Issue by GregPlowman** [JuliaMath/DoubleFloats.jl#201]
Is this the expected result?
```
# DoubleFloats v1.3.8
sqrt(zero(Double64) / 0)
ERROR: DomainError with sqrt(x) expects x >= 0:
```

Differs from earlier version and Float64:
```
# DoubleFloats v1.3.6
sqrt(zero(Double64) / 0)
NaN
```

```
sqrt(zero(Float64) / 0)
NaN
```

**Comment by JeffreySarnoff** [comment]
hmm

**Comment by GregPlowman** [comment]
Here's a comparision with some other extended precision floating point data types:
```
using Quadmath
using MultiFloats
using DoubleFloats

f(::Type{T}) where {T} = sqrt(zero(T) / zero(T))

f(Float64)     # NaN
f(BigFloat)    # NaN
f(Float128)    # -nan
f(Float64x2)   # NaN
f(Double64)    # ERROR: DomainError with sqrt(x) expects x >= 0
```

**Comment by JeffreySarnoff** [comment]
Yes -- I have been involved elsewhere, apologies for the delay.

**Comment by JeffreySarnoff** [comment]
I am spending time to get the current nits in DoubleFloats and one or two
other packages resolved before JuliaCon.  This problem arose with the
merging of another PR.  I will get it fixed or undo that PR this week.
