### ISSUE TITLE
Package compatibility caps

### ISSUE THREAD

**Issue by KZiemian** [JuliaMath/DoubleFloats.jl#21]
Ref: https://discourse.julialang.org/t/package-compatibility-caps/15301

**Comment by saschatimme** [comment]
@KZiemian What do you want to say with this? Got the package capped?

**Comment by JeffreySarnoff** [comment]
I don't know what this is about -- the most recent tag v0.2.0 (awaiting merge) should be used.
There should not be any problem with respect to capping.
