### ISSUE TITLE
Reductions with arrays don't vectorize

### ISSUE THREAD

**Issue by haampie** [JuliaMath/DoubleFloats.jl#22]
For reasons currently beyond me operations with vectors of DoubleFloats don't seem to vectorize when computing inner products, sums and other reductions. For example:

```julia
using DoubleFloats

function my_sum(xs::Vector{T}) where {T}
    s = zero(T)

    for x in xs
        s += x
    end

    return s
end
```

If I run

```
JULIA_LLVM_ARGS="-pass-remarks-analysis=loop-vectorize" julia -O3 -L example.jl -e "my_sum(rand(Double64, 100))"
```

it outputs

```
remark: example.jl:6:0: loop not vectorized: loop control flow is not understood by vectorizer
remark: example.jl:6:0: loop not vectorized: value that could not be identified as reduction is used outside the loop
remark: example.jl:6:0: loop not vectorized: loop control flow is not understood by analyzer
```

Removing the branch in https://github.com/JuliaMath/DoubleFloats.jl/blob/master/src/math/ops/op_dbdb_db.jl#L3 does not seem to fix the issue.

**Comment by haampie** [comment]
Thanks for your reply! I was aware that it uses SSE, but I wondered whether it could use AVX instructions in the reductions. That can really make a big difference. Just as an illustration with `Vector{Float64}`:

```julia
using BenchmarkTools

function sum_vectorized(xs::Vector{T}) where {T}
    s = zero(T)
    for x in xs
        @fastmath s += x # this is required for vectorization, so my code on top is a bit flawed then
    end
    s
end

function sum_not_vectorized(xs::Vector{T}) where {T}
    s = zero(T)
    for x in xs
        s += x
    end
    s
end

@btime sum_vectorized(v) setup = (v = rand(1000));
#  102.719 ns (0 allocations: 0 bytes)

@btime sum_not_vectorized(v) setup = (v = rand(1000));
#  1.100 μs (0 allocations: 0 bytes)
```

so there is a 10x speedup. `sum_vectorized` does unrolling and uses AVX, while `sum_not_vectorized` does not unroll the loop and uses SSE.

I'm not claiming the same could work for DoubleFloats.jl, but just genuinely curious if we could get better performance in reductions.

**Comment by saschatimme** [comment]
Isn't `vaddsd` already an AVX instruction?

**Comment by haampie** [comment]
I think you have to look at the registers that are used: if it's `xmm` then it's SSE, if it's `ymm` then it's AVX

**Comment by saschatimme** [comment]
Yeah I also figured that a second after I wrote it ^^

I think this is a very hard problem. You cannot use the `@fastmath` macro since the order of the arithmetic operations in the addition is important.

But maybe it is possible to do two separate additions simultaneously. It would probably be worth a try to interleave two additions by hand and to see whether LLVM uses AVX then.

**Comment by haampie** [comment]
> But maybe it is possible to do two separate additions simultaneously. It would probably be worth a try to interleave two additions by hand and to see whether LLVM uses AVX then.

Yeah, maybe I should have tried by hand before opening the issue!

For what it's worth, commenting out the branch in https://github.com/JuliaMath/DoubleFloats.jl/blob/master/src/math/ops/op_dbdb_db.jl#L3 simplifies the loop body a little bit (I think it is also necessary to even allow vectorization) and gives a tiny edge of performance:

```
@btime my_sum(v) setup = (v = rand(Double64, 10_000))
```

on master 145.690 μs, but with the branch commented out 125.977 μs.

Let me just close this issue until I can demonstrate that better performance is actually possible ^^

**Comment by JeffreySarnoff** [comment]
I don't see how to involve AVX without special casing a version of this package.  That said -- would be nice.
