### ISSUE TITLE
inv_pi1o1_t64 not defined

### ISSUE THREAD

**Issue by jverzani** [JuliaMath/DoubleFloats.jl#23]
On the most recent release, v0.2.0, this error message is given when finding `tan(Double64(4.0))`:
```
julia> tan(Double64(4.0))
ERROR: UndefVarError: inv_pi1o1_t64 not defined
Stacktrace:
 [1] modpi(::DoubleFloat{Float64}) at /Users/verzani/.julia/packages/DoubleFloats/w6zrB/src/math/arithmetic/modpi.jl:46
```

**Comment by jverzani** [comment]
It seems that it should be `inv_pi_1o1_t64 `. It appears twice in that file.

**Comment by JeffreySarnoff** [comment]
thank you -- it was a copy/paste error and more values were incorrectly named.
It is fixed in master AFAIK.

**Comment by jverzani** [comment]
Happy to help. Thanks for the quick fix.

**Comment by JeffreySarnoff** [comment]
done
