### ISSUE TITLE
Improve code coverage

### ISSUE THREAD

**Issue by saschatimme** [JuliaMath/DoubleFloats.jl#28]
Now that code coverage is finally working, it shows that so far 80% of all lines are covered. In particular it seems that for certain functions not all branches are covered. I think it would be great if we get to near 100% coverage.

You can see the detailed statistics [here](https://codecov.io/gh/JuliaMath/DoubleFloats.jl/tree/master/src).

**Comment by JeffreySarnoff** [comment]
why did you get rid of coveralls?

**Comment by saschatimme** [comment]
`Coveralls.submit` threw an error, but `Codecov.submit` ran fine. We can try to get Coveralls also working again, but maybe this is probably an issue in the `Coverage` package.

**Comment by JeffreySarnoff** [comment]
you are invited to add some coverage tests to any code that works for that for you
