### ISSUE TITLE
muladd and fma with broken since DoubleFloats v0.3.2 (regression)

### ISSUE THREAD

**Issue by oschulz** [JuliaMath/DoubleFloats.jl#32]
I'm getting a strange behavior of `muladd` and `fma` with DoubleFloats v0.3.2. `muladd` returns a tuple instead of a `DoubleFloat` and `fma` fails:

```
julia> muladd(2.0, DoubleFloat(3.0), 4.0)
(10.0, 0.0)

julia> typeof(muladd(2.0, DoubleFloat(3.0), 4.0))
Tuple{Float64,Float64}

julia> fma(2.0, DoubleFloat(3.0), 4.0)
ERROR: UndefVarError: x?? not defined
Stacktrace:
 [1] fma(::Float64, ::Float64, ::Float64, ::Float64, ::Float64, ::Float64) at /user/.julia/packages/DoubleFloats/gB9qU/src/math/arithmetic/fma.jl:38
 [2] fma at /user/.julia/packages/DoubleFloats/gB9qU/src/math/arithmetic/fma.jl:53 [inlined]
 [3] fma(::Float64, ::DoubleFloat{Float64}, ::Float64) at ./promotion.jl:347
 [4] top-level scope at none:0

julia> versioninfo()
Julia Version 1.0.1
Commit 0d713926f8 (2018-09-29 19:05 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
```

With DoubleFloat v0.3.1, all was fine:

```
julia> muladd(2.0, DoubleFloat(3.0), 4.0)
1.0e+01

julia> typeof(muladd(2.0, DoubleFloat(3.0), 4.0))
DoubleFloat{Float64}

julia> fma(2.0, DoubleFloat(3.0), 4.0)
1.0e+01
```

**Comment by JeffreySarnoff** [comment]
fixed on master and latest tag v0.3.3
(problem with github pasting unicode)
we now have better (more accurate) fma and muladd is like the old fma was
we also have more performant matrix multiply

**Comment by JeffreySarnoff** [comment]
...if you would reopen this so others can see it until the new release merges (probably tonight)...

**Comment by JeffreySarnoff** [comment]
All the problematic Unicode typography seems to be removed from the current master and tag v0.3.4.
The fma and muladd routines are working with mixed (FloatNN, DoubleNN) argument types.
Your attentiveness was a help.

**Comment by oschulz** [comment]
Thanks for the quick fix, Jeff!
