### ISSUE TITLE
CI failures

### ISSUE THREAD

**Issue by saschatimme** [JuliaMath/DoubleFloats.jl#4]
It seems that the CI is currently setup such that only 0.7 is tested but also tests on 0.7 are allowed to fail, i.e., the tests will always pass.

**Comment by JeffreySarnoff** [comment]
There was a problem with CI and v0.7 -- it was necessary to set this up like that or nothing worked (Julia version unavailable or a message something like that) -- even though all tests passed run locally.  I will change it over the weekend and see if that still happens.

**Comment by JeffreySarnoff** [comment]
fixed
