### ISSUE TITLE
Matmul only works for square matrizes

### ISSUE THREAD

**Issue by mfalt** [JuliaMath/DoubleFloats.jl#45]
Matmul is not working.
For some reason, the special matmul was implemented to only work for square matrices.
It also doesn't support zero dimensions. 
PR incoming

**Comment by JeffreySarnoff** [comment]
Thank you for the attention.  I will tag a new release tonight, with the remedy.

**Comment by JeffreySarnoff** [comment]
merged your PR

**Comment by JeffreySarnoff** [comment]
tagged as version 0.6.1 -- likely to merge this evening
