### ISSUE TITLE
Support Complex{DoubleFloat{T}}?

### ISSUE THREAD

**Issue by mcabbott** [JuliaMath/DoubleFloats.jl#48]
I ran into the following problem today:
```
julia> using DoubleFloats

julia> sin(1.0 + 0im)
0.8414709848078965 + 0.0im

julia> sin(Double64(1) + 0im)
0.0 + 0.0im

julia> cos(Double64(1) + 0im)
0.0 + 0.0im

julia> tan(Double64(1) + 0im)
ERROR: InexactError: Int64(NaN)
```
I don't see this for nonzero imaginary part: 
```
julia> sin(Double64(1) + im) ≈ sin(1.0 + im)
true
```

**Comment by JeffreySarnoff** [comment]
There is no overt support for Complex{DoubleFloat{T}}.  Nonetheless, your case is of interest.
@saschatimme any thoughts?

**Comment by JeffreySarnoff** [comment]
The problem seems to be with `cosh(0`)` ...

**Comment by JeffreySarnoff** [comment]
The right way to address this is to provide specific functions for Complex{DoubleFloat{T}}.
Thank you @mcabbott for raising this -- you pulled a thread that needed to be addressed.

**Comment by mcabbott** [comment]
Great, many thanks for having a look. I didn't realise Complex wasn't supported, but would obviously be pleased if it ends up being so. 

Here is the other weird complex bug I ran into:
```
julia> Double64(2.562509242163081) - Double64(6.620014612301146)*im             
2.562509242163081 - 6.620014612301146im

julia> exp(ans)                                                                 
ERROR: MethodError: no method matching two_sum(::Float64, ::Float64, ::Float64)
Closest candidates are:
  two_sum(::T<:Union{Float16, Float32, Float64}, ::T<:Union{Float16, Float32, Float64}) where T<:Union{Float16, Float32, Float64} at /Users/me/.julia/packages/DoubleFloats/cH02I/src/math/errorfree.jl:19
Stacktrace:
 [1] mod2pi(::DoubleFloat{Float64}) at /Users/me/.julia/packages/DoubleFloats/cH02I/src/math/arithmetic/modpi.jl:100
 [2] sin_kernel(::DoubleFloat{Float64}) at /Users/me/.julia/packages/DoubleFloats/cH02I/src/math/elementary/trig.jl:167
```

**Comment by JeffreySarnoff** [comment]
I recognize that bug -- on it.

**Comment by JeffreySarnoff** [comment]
I just tagged v0.6.2, try `pkg> rm DoubleFloats` `pkg> add DoubleFloats#master`.  Your complex stuff may work (and let me know what fails, if you find that).  It will help as I consider how to make Complex more robust here. (the mod2pi issue is also fixed).

**Comment by JeffreySarnoff** [comment]
these fixes have been merged

**Comment by saschatimme** [comment]
> There is no overt support for Complex{DoubleFloat{T}}. Nonetheless, your case is of interest.

I think most things should work out of the box and use the generic `Complex` implementations. But at least for me it would be interesting if there is a performance gain if we specialize basic complex arithmetic with DoubleFloats.

**Comment by mcabbott** [comment]
Thanks, I just tried everything on master. Some tests which fail for me are: 
```
julia> tanh(Double64(1) + 0im)
ERROR: InexactError: Int64(NaN)

julia> asin(Double64(1) + 0im)
ERROR: DomainError with sin(x) only defined for finite x:
```

**Comment by JeffreySarnoff** [comment]
ComplexD64, ComplexD32, ComplexD16 with elementary functions

**Comment by mcabbott** [comment]
Thanks for the release! Sadly I just found one more error case:
```
julia> x = Double64(-1.168869267851442e79) + Double64(4.140780141319954e87)*im                                                                      
-1.168869267851442e79 + 4.140780141319954e87im

julia> exp(Complex{Float64}(x))                                           
0.0 + 0.0im

julia> exp(x)                                                             
ERROR: InexactError: trunc(Int64, 6.590256277478276e86)
Stacktrace:
 [1] trunc at ./float.jl:696 [inlined]
 [2] mod2pi(::DoubleFloats.DoubleFloat{Float64}) at /Users/me/.julia/packages/DoubleFloats/IavWq/src/math/arithmetic/modpi.jl:100
 [3] cos_kernel(::DoubleFloats.DoubleFloat{Float64}) at /Users/me/.julia/packages/DoubleFloats/IavWq/src/math/elementary/trig.jl:188
```

**Comment by JeffreySarnoff** [comment]
not so sad -- it is your use that is shaking out what needs to be addressed
This package has been in great need of such attention from a user -- and I am grateful.

**Comment by JeffreySarnoff** [comment]
@mcabbott tracked it down, should be ok in v0.7.2 (master) -- added your case to the tests.
