### ISSUE TITLE
iseven and isodd don't work if the argument is an integer value

### ISSUE THREAD

**Issue by ScottPJones** [JuliaMath/DoubleFloats.jl#57]
Both `iseven(d64"2")` and `isodd(d64"2")` give method errors, because `iseven` and `isodd` are not normally defined for floating point types such as `Float64`.

**Comment by JeffreySarnoff** [comment]
ok thanks will fix this weekend

**Comment by JeffreySarnoff** [comment]
ok thanks will fix this weekend

**Comment by JeffreySarnoff** [comment]
fixed
