### ISSUE TITLE
The constructor macro `d64"..."` for `DoubleFloat{Float64}` conflicts with `d64` from `DecFP.jl`.

### ISSUE THREAD

**Issue by ScottPJones** [JuliaMath/DoubleFloats.jl#58]
The IEEE Decimal Floating Point package, `DecFP.jl`, has been around for almost 4 years now.
It would be nice if the string macro for this package did not conflict, so people could use both packages.
I'd suggest it be changed to `df64`.

**Comment by JeffreySarnoff** [comment]
I acknowledge that. :)
thanks for the info, will look at it next week.

Meanwhile, if this is an issue for others:
use the fully elaborated forms (PkgName.d64)

**Comment by ScottPJones** [comment]
Besides `DecFP` having been around longer, it is for IEEE standard formats, so I'd hope that the shorter `d32`, `d64`, and `d128` string macro names can continue to be used.
The problem is, if you load both, then you can't use *either* of them without the package name.

**Comment by JeffreySarnoff** [comment]
I understand.

**Comment by ScottPJones** [comment]
You also seem to be involved in Quadmath.jl, which implements the IEEE `Float128` type.  Has that defined any string macros also that might conflict?

**Comment by JeffreySarnoff** [comment]
^ not yet
^^^ I have been on top of this.  The present master exports df64_str etc and notes that d64_str etc are going away.  For the moment, I created a branch here `df` that does not export d64_str etc, ony df64_str etc.  I have to be careful about how I transition master -- its in the queue.

**Comment by ScottPJones** [comment]
I wonder if `b128` would be appropriate for `Float128` that `Quadmath.jl` supports.
It might make sense to extend it, so that: `b16`, `b32`, `b64`, `b128`, and `b256` were all defined for the IEEE binary floating point types, and `d32`, `d64`, and `d128` defined for the IEEE decimal floating point types.

`DecFP` might also want to had `bid32`, `bid64`, and `bid128` as synonyms, so that if I get pack to wrapping or reimplementing the `decNumber` package, it could use `dpd32`, `dpd64`, and `dpd128`,
which are supported directly on IBM mainframes.  The `d32`... forms could possibly been made to select one or the other IEEE representation based on a compile time flag.

**Comment by JeffreySarnoff** [comment]
use of d64 etc now warns of deprecation
