### ISSUE TITLE
Quick v0.7.11 bugfix release?

### ISSUE THREAD

**Issue by oschulz** [JuliaMath/DoubleFloats.jl#61]
Could you do a quick v0.7.11 bugfix release to get commit 915ebeb in? The typo fixed there is currently breaking BAT.jl.

**Comment by oschulz** [comment]
Found a fairly easy workaround, so BAT.jl is fixed.

**Comment by JeffreySarnoff** [comment]
tagged 0.7.11 merge pending

**Comment by oschulz** [comment]
Thanks a lot!
