### ISSUE TITLE
missing parse/tryparse

### ISSUE THREAD

**Issue by stevengj** [JuliaMath/DoubleFloats.jl#64]
Your `Base.tryparse` implementation is [currently commented out](https://github.com/JuliaMath/DoubleFloats.jl/blob/be1a822ae548736ff4aba7a82573dbe4c358a062/src/type/parse.jl#L86), which means that e.g. `parse(Double64, "3.2")` fails with a `MethodError`.

(This breaks ChangePrecision.jl among other things.)

**Comment by JeffreySarnoff** [comment]
thanks. on it.

**Comment by JeffreySarnoff** [comment]
fixed in v0.7.14 .. merge pending

**Comment by JeffreySarnoff** [comment]
merged
