### ISSUE TITLE
Problem with accuracy of sinpi?

### ISSUE THREAD

**Issue by daanhb** [JuliaMath/DoubleFloats.jl#65]
I came across this weird output of `sinpi`:
```julia
julia> sinpi(sqrt(2))
-0.9639025328498774

julia> sinpi(sqrt(Double64(2)))
-0.2662553420414155

julia> sinpi(sqrt(BigFloat(2)))
-0.9639025328498773302883368552795782761203067465991152157249104129629695305684294

julia> cospi(sqrt(2))
-0.2662553420414152
```
It seems the result for `Double64` is wrong, and `sinpi` seems to return the value of `cospi` for this argument. I looked at the `sinpi` implementation in Base, since the issue may be there, but could not easily see what went wrong. I'll look further into it, but am posting this issue in the meantime.

**Comment by daanhb** [comment]
For context, I was trying out the implementation of a generic FFT in FastTransforms.jl (by @MikaelSlevinsky) with `Double64` types, looking for something that would be more accurate than `Float64` but faster than using `BigFloat`. I obtained not more than 1e-15 accuracy from the FFT of an array of `Double64`'s and I decided to chase the offending issue (or issues for that matter, it is not working yet).

Anyhow, looking at `sinpi` in Base the erroneous computation seems like it might be due to assumptions that are made about the rounding mode which are not valid for `Double64` numbers. This is a condensed example of what happens in `sinpi` [here](https://github.com/JuliaLang/julia/blob/8221c87b09b8456f4fe422ee2d8756a2a2630c7b/base/special/trig.jl#L781), as part of a computation to reduce the argument to the interval [-1,1]:
```julia
julia> using DoubleFloats

julia> t1 = maxintfloat(Float64)*3/2
1.3510798882111488e16

julia> ((sqrt(2)+t1)-t1)
2.0

julia> t2 = maxintfloat(BigFloat)*3/2
1.73688133855974293135356477513031861779904976998460846059186376011869694459904e+77

julia> ((sqrt(BigFloat(2))+t2)-t2)
2.0

julia> t3 = maxintfloat(Double64)*3/2
1.2169445762191004e32

julia> ((sqrt(Double64(2))+t3)-t3)
1.5
```
There is nothing special about the value sqrt(2), it is just an example. Presumably, the value 1.5 rather than 2.0 is due to different rounding at large values. (I could be wrong here, I'm not familiar with this technique). I'm not sure if this is something that `Double64` could control, or if an alternative definition of `sinpi` should be used?

It also seems like perhaps the rounding assumption should be verified in Base, if that is possible.

**Comment by JeffreySarnoff** [comment]
Thanks for raising the issue. I'll look into it.

**Comment by JeffreySarnoff** [comment]
I had not defined sinpi, cospi for DoubleFloats -- I'll add them presently.

**Comment by JeffreySarnoff** [comment]
Fixed in release tagged 0.7.19 (also provided `tanpi`).

**Comment by daanhb** [comment]
Great, thanks for the quick response!

**Comment by daanhb** [comment]
The generic FFT I was going for now works with full accuracy (hurray!), but I encountered two more issues.

First, a minor one. Converting pi to a `Complex{Double64}` results in an ambiguity error:
```julia
julia> convert(Complex{BigFloat}, π)
3.141592653589793238462643383279502884197169399375105820974944592307816406286198 + 0.0im

julia> convert(Complex{Double64}, π)
ERROR: MethodError: Complex{DoubleFloat{Float64}}(::Irrational{:π}) is ambiguous. Candidates:
  (::Type{Complex{T}})(x::AbstractIrrational) where T<:Real in Base at irrationals.jl:30
  (::Type{Complex{DoubleFloat{Float64}}})(x::T) where T<:Real in DoubleFloats at /home/daan/.julia/packages/DoubleFloats/URN5e/src/Double.jl:45
Possible fix, define
  Complex{DoubleFloat{Float64}}(::AbstractIrrational)
Stacktrace:
 [1] convert(::Type{Complex{DoubleFloat{Float64}}}, ::Irrational{:π}) at ./number.jl:7
 [2] top-level scope at none:0
```
That's easy to work around in my code (using `real(T)` rather than `T` here and there).

Next, a more serious one. Making a linear range using `Double64` results in Float64 accuracy. It is due to the `lerpi` function in Base [here](https://github.com/JuliaLang/julia/blob/master/base/range.jl#L658). The line `j/d` with j and d both integers is the offending one. There is a special case method for BigFloats.

Example:
```julia
julia> k1 = range(zero(Double64), stop = 5, length = 6)
6-element LinRange{DoubleFloat{Float64}}:
 0.0,1.0,2.0,3.0,4.0,5.0

julia> k2 = range(zero(BigFloat), stop = 5, length = 6)
6-element LinRange{BigFloat}:
 0.0,1.0,2.0,3.0,4.0,5.0

julia> k1[3]-k2[3]
1.1102230246251565404236316680908203125e-16
```
Overwriting `Base.lerpi` fixes the issue. Here, too, I feel the implementation in Base could be done in a safer way.

Sorry for continuing a closed issue. After this first successful experiment, I'm tempted to run the full test suite of a package I'm working on (unregistered) with Double64 to see what else comes up, and I'll group the issues (if any)!

**Comment by JeffreySarnoff** [comment]
I am glad to get the helpful information.  What does "Base.lerpi" do? integer lerping?
Please post the fixes you used (it will get me started more quickly).

**Comment by daanhb** [comment]
At the prompt, I wrote this:
```julia
import Base: lerpi
function lerpi(i::Int, j::Int, a::Double64, b::Double64)
       t = Double64(i)/j
       (1-t)*a+t*b
end
```
I.e., I converted one of the integers to `Double64`. I did not check the other types that DoubleFloats defines, I just wanted to try this one.

I'm not familiar with this function, but apparently MPFR implements it:
```julia
julia> @which Base.lerpi(1, 2, big(0.0), big(1.0))
lerpi(j::Integer, d::Integer, a::BigFloat, b::BigFloat) in Base.MPFR at mpfr.jl:1030
```

**Comment by daanhb** [comment]
Here is another unexpected result:
```julia
julia> eltype(Float64)
Float64

julia> eltype(BigFloat)
BigFloat

julia> eltype(Double64)
Float64
```
The outcome of the last statement is due to [this line](https://github.com/JuliaMath/DoubleFloats.jl/blob/master/src/Double.jl#L262) and the line following it in Double.jl. I'm not sure what the intention of this code is. However, to be consistent, I think the element type of a DoubleFloat should be the type itself, because that's what you get when you index a number:
```julia
julia> d = Double64(1)
1.0

julia> typeof(d[1])
DoubleFloat{Float64}

julia> eltype(d)
Float64
```

**Comment by JeffreySarnoff** [comment]
very good catch -- just edited that

**Comment by JeffreySarnoff** [comment]
The Package management system is being upgraded and revamped today and tomorrow.
To use these changes `pkg> add DoubleFloats#master` (untested -- probably ok :))

**Comment by daanhb** [comment]
Indeed, that works! Thanks.

I am mainly fixing bugs I'm finding in my own code now. The latest issue I encountered was when using `gamma(x)` where `x` is a DoubleFloat and gamma is a function from SpecialFunctions.jl. That gave a StackOverflowError, but that was due to the lack of a fallback in SpecialFunctions.jl. I added a workaround (in my own package) by converting the argument to a BigFloat and converting the result back.

**Comment by JeffreySarnoff** [comment]
Well, DoubleFloats does not support `gamma` or other exports from SpecialFunctions.  While having that coverage (even through a mechanism similar to the one you used) would be good, there are problems with installing SpecialFunctions (especially on Windows -- where you need to do it in a window that has administrator status).  I have to avoid that sort of consternation until SpecialFunctions fixes the problem (it relates to the use of symbolic file links to the underlying library).

**Comment by daanhb** [comment]
That's fair enough. I was not aware of the issues with SpecialFunctions, but it's very good to know about since I'm relying on that package.

Turns out the gamma issue was the last one. Everything works! Thanks for your quick help!

**Comment by JeffreySarnoff** [comment]
🌊
