### ISSUE TITLE
Output differs from README

### ISSUE THREAD

**Issue by dpsanders** [JuliaMath/DoubleFloats.jl#66]
```
julia> using DoubleFloats
[ Info: Precompiling DoubleFloats [497a8b3b-efae-58df-a0af-a86822472b78]

julia> Double64(0.2)
0.2
```
This is different from the output that is shown in the README. Am I doing something wrong?

**Comment by JeffreySarnoff** [comment]
no all is aright
I have improved the experience and neglected to update the README.  Thanks.

```
julia> using DoubleFloats

julia> Double64(0.2)
0.2

julia> showall(ans)
0.2000000000000000111022302462515654

julia> Double64(2)/10
0.2

julia> showall(ans)
0.1999999999999999999999999999999993


julia> df64"0.2"
0.2

julia> showall(ans)
0.1999999999999999999999999999999993
```

**Comment by JeffreySarnoff** [comment]
The idea is that you see shown what is of the most reliable information and DoubleFloats serves you.

**Comment by JeffreySarnoff** [comment]
Your first impressions are very helpful to me.  Do not hesitate to share your immediate takes.
