### ISSUE TITLE
DoubleFloat(2) doesn't work

### ISSUE THREAD

**Issue by dpsanders** [JuliaMath/DoubleFloats.jl#67]
```
julia> DoubleFloat(2)
ERROR: MethodError: no method matching DoubleFloat(::Int64)
```

**Comment by JeffreySarnoff** [comment]
Hmm -- you should be using `Double64`, `DoubleFloat` needs a Float type `DoubleFloat{Float64}`
`Double64(2), DoubleFloat{Float64}(2)` work as intended
I need a way to emphasize that users should use the exported types `Double64` `Double32` `Double16`, `ComplexDF64` `ComplexDF32` `ComplexDF16`.

I'll see if its possible to interpret `DoubleFloat(x::T) where {T<:Union{Signed, AbstractFloat}}` as `Double64(x)` -- not sure offhand, and also not sure its a good idea to do.

**Comment by JeffreySarnoff** [comment]
I see it works with floats `DoubleFloat(1.0)` -- looking to see where I did that.

**Comment by dpsanders** [comment]
Ah I see, thanks.

**Comment by JeffreySarnoff** [comment]
Just tagged v0.7.21 which does allow `DoubleFloat(x)` because there are some packages which need this understood to play well with DoubleFloat (I do not recall which, though).  I'll add more clarity up front in the README and the docs.  It was a good catch.
