### ISSUE TITLE
Package DoubleFloats does not have Random in its dependencies

### ISSUE THREAD

**Issue by rjplevin** [JuliaMath/DoubleFloats.jl#69]
I'm getting this message on attempts to precompile various packages...
`Package DoubleFloats does not have Random in its dependencies`

**Comment by JeffreySarnoff** [comment]
thanks for the note -- a new version was just put through using the new registration and something may have been lost -- checking

**Comment by JeffreySarnoff** [comment]
OK the [dep] for Random has been restored in the current master.
This has been submitted to be registered, and I can only tag the new version after that occurs.
`pkg> add DoubleFloats#master` should take care of this in the meantime
I will let you know when the change is part of the General package registry (it has been taking 1-2days).
At that time, I suggest `pkg> rm DoubleFloats` `pkg> add DoubleFloats` to resync the release.

**Comment by JeffreySarnoff** [comment]
wait -- there is another registrator issue

**Comment by JeffreySarnoff** [comment]
ok, apologies for the glitch, current master does precompile and pass all of its tests

**Comment by rjplevin** [comment]
Thanks for the quick fix!
