### ISSUE TITLE
Warning: Package DoubleFloats does not have LinearAlgebra in its dependencies

### ISSUE THREAD

**Issue by GregPlowman** [JuliaMath/DoubleFloats.jl#70]
Getting this warning with `DoubleFloats v0.7.23`:
```
Julia-1.0.3> using DoubleFloats
[ Info: Precompiling DoubleFloats [497a8b3b-efae-58df-a0af-a86822472b78]
┌ Warning: Package DoubleFloats does not have LinearAlgebra in its dependencies:
│ - If you have DoubleFloats checked out for development and have
│   added LinearAlgebra as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with DoubleFloats
└ Loading LinearAlgebra into DoubleFloats from project dependency, future warnings for DoubleFloats are suppressed.
```
Same warning with Julia v1.1.0

**Comment by JeffreySarnoff** [comment]
what version does  `status` report

**Comment by JeffreySarnoff** [comment]
This message happened with a release yesterday.  I made changes, and someone else who had this problem said it went away with the latest tagged version (v0.7.23).
Have you done `pkg> up'? 
If not, try this `pkg> rm -m DoubleFloats` `pkg> up` `pkg> add DoubleFloats`
Let me know what happens.

**Comment by JeffreySarnoff** [comment]
oh I did not see the version info -- I don't know why this is happening at your computer.
Let me ask on slack.

**Comment by JeffreySarnoff** [comment]
@GregPlowman I thought the fix had been merged -- it is in master and passes, awaiting the uptake.
Until it is merged, I cannot retag master.  (thank you for alerting me)

OK -- The recent fix has not yet been merged into Julia Packages.
You can `add> DoubleFloats#master` and that should make the warning disappear.
Or just ignore the warning in the meantime.
When v0.7.24 merges, `rm DoubleFloats` `up` 1add DoubleFloats` -- I will post here when it does

**Comment by GregPlowman** [comment]
OK. Thanks for the fast response.

**Comment by JeffreySarnoff** [comment]
v0.7.24 has been merged

**Comment by GregPlowman** [comment]
Works now. No warnings.
Thanks!
