### ISSUE TITLE
FFTs

### ISSUE THREAD

**Issue by antoine-levitt** [JuliaMath/DoubleFloats.jl#74]
FFTs aren't supported for double floats. Is there any plan to do this? In principle it should be as simple as following the instructions in https://github.com/JuliaMath/AbstractFFTs.jl.

**Comment by JeffreySarnoff** [comment]
You are the first person to request FFT support.  If it happens to be as easy as that, sure .. its a plan.
I will let you know.

**Comment by JeffreySarnoff** [comment]
One of the instructions is "implement the FFT" for your numeric type.  If that is easy for you, please do.

**Comment by JeffreySarnoff** [comment]
There is not a completed implementation of FFT for AbstractFloats.  That sort of processing is not for me to code.  This will wait until there is one that handles BigFloats; DoubleFloats should work with any algorithmic implementation that works with BigFloats and is not specialized to the internals of BigFloats..

**Comment by antoine-levitt** [comment]
This is actually already implemented by the FastTransforms package : https://github.com/JuliaApproximation/FastTransforms.jl/pull/64

**Comment by JeffreySarnoff** [comment]
If it is there, why were you not using that already?

**Comment by antoine-levitt** [comment]
Because I wasn't aware of it until I read about it from the issue on which you linked to this one :) so this issue can be closed.
