### ISSUE TITLE
Diagonalizability condition in matrixfunction

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaMath/DoubleFloats.jl#77]
Is there a reason why [there](https://github.com/JuliaMath/DoubleFloats.jl/blob/243751cae16b4691295bb35f729366e90158f4eb/src/math/linearalgebra/matrixfunction.jl#L3) the rank of `m` is checked instead of the rank of `evecs`? There are rank deficient matrices that are diagonalizable and full rank matrices that are not.

**Comment by JeffreySarnoff** [comment]
my ignorance -- pls submit a PR

**Comment by JeffreySarnoff** [comment]
or, if you prefer -- just show me how to write that part correctly
