### ISSUE TITLE
typo in DoubleFloats.jl/src/Double.jl lines 42,43

### ISSUE THREAD

**Issue by snoeyink** [JuliaMath/DoubleFloats.jl#79]
While reading code, it appears that lines 42&43 of `DoubleFloats.jl/src/Double.jl`
refer to an undefined type F, which should perhaps be T. (Obviously not important, or someone would have commented before; thanks for your package, which is helping me learn Julia...)
```
@inline LO(x::T) where {T<:IEEEFloat} = zero(F)
@inline HILO(x::T) where {T<:IEEEFloat} = x, zero(F)
```

**Comment by JeffreySarnoff** [comment]
Thank you for the attentiveness.  I do not see those lines in /src/Double.jl.
Would you post the link you used to look at the file?

**Comment by JeffreySarnoff** [comment]
(If you were looking locally, rather than on github, do `]up` in the REPL to get the latest versions of the packages you have added)

**Comment by JeffreySarnoff** [comment]
@snoeyink please read the notes above and let me know what you are seeing.  thanks.

**Comment by snoeyink** [comment]
Thanks for such a rapid reply.  I seem to have gotten a link to an older branch; my apologies  -- the package management is one of the things I'm just figuring out...  https://github.com/JuliaMath/DoubleFloats.jl/blob/d87c49e5a9d7c732d229efbe1118d2cae0c619e6/src/Double.jl

**Comment by JeffreySarnoff** [comment]
I've been there too! You are welcome to ask questions about the package, how parts work, why certain decisions were made. Also, if you have not yet joined Julia's slack -- it is a good place for quick questions (use Discourse for the more substantial ones, or for questions that others will benefit from seeing [slack is temporary]), see "Discourse" and "Chat" here https://julialang.org/community/.
