### ISSUE TITLE
Erf and erfc broken with DoubleFloats

### ISSUE THREAD

**Issue by mfherbst** [JuliaMath/DoubleFloats.jl#90]
All of `erf(Double64(0.1))`, `erfc(Double64(0.1))`, `erf(Double32(0.1))`, `erfc(Double32(0.1))` return a `StackOverflowError` on Julia 1.1 and Julia 1.3 (the versions I tested).

**Comment by JeffreySarnoff** [comment]
There is a problem in an associated package that I use.  Thank you for letting me know. I am pursuing the solution.

**Comment by JeffreySarnoff** [comment]
works for me

**Comment by mfherbst** [comment]
Not for me ... on julia 1.3 with DoubleFloats 1.0.0 I still get:
```
julia> erf(Double64(0.1))
ERROR: StackOverflowError:
Stacktrace:
 [1] erf(::Quadmath.Float128) at /home/mfh/.julia/packages/DoubleFloats/WWrr5/src/math/special/gamma_erf.jl:1 (repeats 80000 times)
```

**Comment by JeffreySarnoff** [comment]
works on julia latest (1.4.0-DEV)  -- I'll keep at it for 1.3

**Comment by JeffreySarnoff** [comment]
what version of 1.3 are you using ?
```
 
  | | |_| | | | (_| |  |  Version 1.3.0-rc3.0 (2019-10-04)
 
julia> using DoubleFloats

julia> erf(5.0)
0.9999999999984626

julia> #  [497a8b3b] DoubleFloats v1.0.0
```

**Comment by JeffreySarnoff** [comment]
(if you are using 1.3.0-rc3.0 or later, maybe try re-adding DoubleFloats, or using DoubleFloats in a new REPL window)

**Comment by mfherbst** [comment]
I re-installed `DoubleFloats`, which did not help, so I still get a `StackOverflowError`. My `versioninfo()` is:
```
Julia Version 1.3.0
Commit 46ce4d7933 (2019-11-26 06:09 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
```
so the release of Julia 1.3. Note, that the code you showed above is not the code I used to trigger the problem, because you are not casting to `Double64`.

**Comment by JeffreySarnoff** [comment]
I fixed it -- please confirm with current master.

**Comment by mfherbst** [comment]
Works like charm, thanks!
