### ISSUE TITLE
Hyperbolic Tangent

### ISSUE THREAD

**Issue by cpross90** [JuliaMath/DoubleFloats.jl#91]
I noticed that in base, the tanh function chooses cut-off input values,

https://github.com/JuliaLang/julia/blob/3648f4cf9921cfdc4384782f20702593fad1310a/base/special/hyperbolic.jl

```julia
a = Double64(708)
b = Double64(709)
c = float(1024)

tanh(a) # 1.0
tanh(b) # NaN
tanh(c) # 1.0
```

I can fix this locally by doing something similar, but I thought I would get input since I didn't see anything in Discourse or past issues on this.

**Comment by JeffreySarnoff** [comment]
you found an important bug; thank you 
there is a similar problem with other trig and hyperbolic trig functions.
will fix

**Comment by JeffreySarnoff** [comment]
fixed, merge pending
