### ISSUE TITLE
Inf operations return NaN

### ISSUE THREAD

**Issue by vincentcp** [JuliaMath/DoubleFloats.jl#94]
#86 was closed in which was mentioned that elementary operations involving `Inf` such as 
``` julia
>julia Double64(Inf)*2
Inf
```
are  fixed. However, 

``` julia
>julia Double64(2)*Inf
NaN
```
still has some issues.

**Comment by vincentcp** [comment]
And in the same line
``` julia
julia> norm(rand(Double64,4,4),Double64(Inf))
NaN
julia> norm(rand(Double64,4,4),Inf)
NaN
```

**Comment by JeffreySarnoff** [comment]
ok -- looking at this

**Comment by JeffreySarnoff** [comment]
Thank you for this note.  It is fixed in master, pending merge.

**Comment by JeffreySarnoff** [comment]
Both parts are fixed in master, pending merge.  Please let me know if you encounter other issues.
