### ISSUE TITLE
Double64(-0.0) != 0

### ISSUE THREAD

**Issue by RalphAS** [JuliaMath/DoubleFloats.jl#96]
This breaks various things.  For example it makes it impossible for a `Complex{Double64}` matrix to satisfy `ishermitian()`.

**Comment by JeffreySarnoff** [comment]
Well, that's no good at all.

**Comment by JeffreySarnoff** [comment]
`iszero(Double64(-0.0))` works
fixing the`==` and  `!=` tests ...

**Comment by JeffreySarnoff** [comment]
fixed on master, pending merge
