### ISSUE TITLE
Supnorm and DoubleFloats can give nan

### ISSUE THREAD

**Issue by pkofod** [JuliaMath/DoubleFloats.jl#99]
I ran into a problem where my  optimization could would report failure, because the sup norm of the gradient was NaN at the candidate optimum.
```
julia> g = DoubleFloat{Float64}[-4.118744257705127e-218, 4.0018189788207504e-218]
2-element Array{DoubleFloat{Float64},1}:
 -4.118744257705127e-218 
  4.0018189788207504e-218

julia> norm(g, Inf)
NaN
```

**Comment by JeffreySarnoff** [comment]
Are you using the latest release v1.1.3? `]pkg> up`

**Comment by JeffreySarnoff** [comment]
@pkofod apologies for the delay -- was otherwise engaged.

**Comment by JeffreySarnoff** [comment]
You were right about this -- I had an unregistered version.
Thank you for the notification.  It is fixed in the new version (current master), pending release.

**Comment by pkofod** [comment]
Great, thanks! I'm using DoubleFloats as an example of converging to very tight tolerances, so it was a bit unfortunate I could not show this example :)  As you see it is indeed converged to an extremely small tolerance, but the default printing would say NaN and failed convergence! )
